/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BakeryAdmin2026RouteImport } from './routes/bakery-admin-2026'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryAdmin2026Route = BakeryAdmin2026RouteImport.update({
  id: '/bakery-admin-2026',
  path: '/bakery-admin-2026',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bakery-admin-2026': typeof BakeryAdmin2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakery-admin-2026': typeof BakeryAdmin2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bakery-admin-2026': typeof BakeryAdmin2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bakery-admin-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bakery-admin-2026'
  id: '__root__' | '/' | '/bakery-admin-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakeryAdmin2026Route: typeof BakeryAdmin2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery-admin-2026': {
      id: '/bakery-admin-2026'
      path: '/bakery-admin-2026'
      fullPath: '/bakery-admin-2026'
      preLoaderRoute: typeof BakeryAdmin2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakeryAdmin2026Route: BakeryAdmin2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
